#!/Users/salesky/anaconda/bin/python
# ---------------------------------------------
# Name: HW3_Starter_Script.py
# Author: Scott Salesky
# University of Oklahoma
# Date: Tue Jun 26 12:29:36 CDT 2018
# Purpose: METR3613 starter script for homework #3: 
# Analysis and discussion of Mesonet data with Python
# ---------------------------------------------

#Import needed libraries
import numpy as np                  
import scipy as sp                  
import matplotlib.pyplot as plt    
from matplotlib import rc         
import functions as lib          
import os

# lib.get_meso_file(2018,6,24,'nrmn')
# lib.get_meso_file(2018,6,24,'nrmn','./data/')
# lib.get_meso_file(2018,6,24,'nwcm','./data/')

# Define important parameters
y = 2018
m = 5
siteID='nrmn'       #ID of selected Mesonet site
siteName='Norman'   #Full name of Mesonet site, used for Figure titles

# Determine number of days in the month
m31 = [1,3,5,7,8,10,12]
m30 = [4,6,9,11]
m28 = 2

if any(m == mo for mo in m31):
    nd=31
elif any(m == mo for mo in m30):
    nd=30
else:
    nd=28

# Define directories for .mts files (data files from Mesonet), .png (plots
# generated by the script), and .dat files (ASCII files with daily statistics)
datadir = './data/'         #File where Mesonet .mts data will be saved
pngdir = './png_files/'     #File where .png files will be saved
statdir = './stat_files/'   #File where ASCII statistic files will be saved

#Create directories if they don't exist
if not os.path.exists(datadir):
    os.makedirs(datadir)
if not os.path.exists(pngdir):
    os.makedirs(pngdir)
if not os.path.exists(statdir):
    os.makedirs(statdir)

#Allocate arrays for daily statistics
relh_daily = np.zeros(nd,dtype='float')
tair_daily = np.zeros(nd,dtype='float')
tdew_daily = np.zeros(nd,dtype='float')
wspd_daily = np.zeros(nd,dtype='float')
wdir_daily = np.zeros(nd,dtype='float')
pres_daily = np.zeros(nd,dtype='float')
srad_daily = np.zeros(nd,dtype='float')

#Download Mesonet files from the archive using the provided script.
#The .mts files will be downloaded to your computer in the directory/folder that
#you specify above as 'datadir.' Note that you can comment out this section
#once you have run the script for the first time and the .mts files are saved
#on your computer.

# for d in range(1,nd+1):
#     lib.get_meso_file(y,m,d,siteID,outdir=datadir)

#Begin the actual data processing, similar to what we did in HW2
for d in range(1,nd+1):

    #Define the filename
    filename = datadir + str(y) + str(m).zfill(2) + str(d).zfill(2) + siteID + '.mts'
    print filename

    #Read in the data file using the mesonet_importfile() function that we used in HW#2
    [STID, STNM, TIME, RELH, TAIR, WSPD, _, WDIR, _, _, _, RAIN,
            PRES, SRAD, TA9M, WS2M, _, _, _, _, _, _, _, _] = lib.mesonet_importfile(filename)

    #Replace any flagged/missing Mesonet data by NaN 
    RELH[RELH<-100]=np.nan
    TAIR[TAIR<-100]=np.nan
    WSPD[WSPD<-100]=np.nan
    WDIR[WDIR<-100]=np.nan
    PRES[PRES<-100]=np.nan
    SRAD[SRAD<-100]=np.nan
    TA9M[TA9M<-100]=np.nan
    WS2M[WS2M<-100]=np.nan

    #Convert time from minutes into hours
    HOURS = TIME/60.

    #Calculate the dewpoint



    # ---------------------------------------------
    #Prepare daily plots 
    # ---------------------------------------------
    titletext = siteName + ', ' + str(m).zfill(2) + '-' + str(d).zfill(2) + '-' + str(y)
    print titletext

    #Set up options for plots
    plt.figure(figsize=(6,8),dpi=900,facecolor=None,linewidth=2.0)
    rc('font',weight='normal',size=12,serif='Computer Modern Roman')
    rc('savefig',dpi=900)
















